-- TAAMEER Agent Campaign Hub — agent readiness, budgets, campaigns and secure credentials.
create or replace function public.agent_campaign_module_access()
returns boolean language sql stable security invoker set search_path = '' as $$
  select coalesce((select p.status='active' and coalesce(p.modules,'[]'::jsonb) ? 'agent-campaigns'
    from public.profiles p where p.id=(select auth.uid())),false);
$$;

create table if not exists public.agent_campaign_user_permissions (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  can_manage_budget boolean not null default false,
  can_manage_accounts boolean not null default true,
  can_view_credentials boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agent_campaign_agents (
  id uuid primary key default gen_random_uuid(),
  hr_employee_id text,
  legacy_agent_id text,
  full_name_en text not null check (char_length(btrim(full_name_en)) between 2 and 180),
  full_name_ar text,
  department_team text,
  company_email text,
  work_phone text,
  profile_photo_url text,
  employment_status text not null default 'pending_hr' check (employment_status in ('active','pending_hr','inactive','offboarded')),
  source text not null default 'manual' check (source in ('manual','ig_sheet','hr_import')),
  assigned_specialist uuid references public.profiles(id) on delete set null,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists agent_campaign_agents_email_unique on public.agent_campaign_agents(lower(company_email)) where company_email is not null and btrim(company_email)<>'';
create index if not exists agent_campaign_agents_specialist_idx on public.agent_campaign_agents(assigned_specialist);

create table if not exists public.agent_campaign_accounts (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid not null unique references public.agent_campaign_agents(id) on delete cascade,
  platform text not null default 'instagram' check (platform in ('instagram','facebook','tiktok','other')),
  username text,
  profile_url text,
  category text,
  license_no text,
  status text not null default 'no_account' check (status in ('no_account','setup_required','under_setup','access_pending','ready','campaign_active','paused','offboarded')),
  bio_status text not null default 'missing' check (bio_status in ('missing','code_needed','done')),
  profile_setup_status text not null default 'missing' check (profile_setup_status in ('missing','in_progress','done')),
  two_factor_enabled boolean not null default false,
  credentials_saved boolean not null default false,
  profile_picture_approved boolean not null default false,
  bio_added_correctly boolean not null default false,
  agent_informed boolean not null default false,
  stories_permission boolean not null default false,
  account_created_date date,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists agent_campaign_accounts_username_unique on public.agent_campaign_accounts(lower(username)) where username is not null and btrim(username)<>'';
create index if not exists agent_campaign_accounts_status_idx on public.agent_campaign_accounts(status);

create table if not exists public.agent_campaign_credentials (
  account_id uuid primary key references public.agent_campaign_accounts(id) on delete cascade,
  secret_id uuid not null unique,
  login_email text,
  recovery_email text,
  recovery_phone text,
  last_rotated_at timestamptz not null default now(),
  updated_by uuid not null references public.profiles(id),
  updated_at timestamptz not null default now()
);
create table if not exists public.agent_campaign_credential_audit (
  id bigint generated by default as identity primary key,
  account_id uuid not null references public.agent_campaign_accounts(id) on delete cascade,
  actor_id uuid not null references public.profiles(id),
  action text not null check (action in ('saved','revealed','copied')),
  created_at timestamptz not null default now()
);
create index if not exists agent_campaign_credential_audit_account_idx on public.agent_campaign_credential_audit(account_id,created_at desc);

create table if not exists public.agent_campaign_months (
  id uuid primary key default gen_random_uuid(),
  month_start date not null unique check (month_start=date_trunc('month',month_start)::date),
  total_budget numeric(14,2) not null default 0 check (total_budget>=0),
  currency text not null default 'QAR',
  status text not null default 'open' check (status in ('planning','open','locked','closed')),
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.agent_campaign_allocations (
  id uuid primary key default gen_random_uuid(),
  month_id uuid not null references public.agent_campaign_months(id) on delete cascade,
  agent_id uuid not null references public.agent_campaign_agents(id) on delete cascade,
  allocated_budget numeric(14,2) not null default 0 check (allocated_budget>=0),
  priority text not null default 'normal' check (priority in ('low','normal','high','priority')),
  notes text,
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  unique(month_id,agent_id)
);
create index if not exists agent_campaign_allocations_agent_idx on public.agent_campaign_allocations(agent_id);

create table if not exists public.agent_campaign_campaigns (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid not null references public.agent_campaign_agents(id) on delete cascade,
  account_id uuid references public.agent_campaign_accounts(id) on delete set null,
  month_id uuid references public.agent_campaign_months(id) on delete set null,
  name text not null check (char_length(btrim(name)) between 2 and 200),
  project_name text,
  objective text not null default 'leads' check (objective in ('awareness','traffic','engagement','messages','leads','sales','other')),
  status text not null default 'draft' check (status in ('draft','scheduled','active','learning','paused','completed','cancelled')),
  budget numeric(14,2) not null default 0 check (budget>=0),
  start_date date,
  end_date date,
  target_location text,
  ad_manager_url text,
  reference_code text,
  notes text,
  assigned_specialist uuid references public.profiles(id) on delete set null,
  created_by uuid not null references public.profiles(id),
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date is null or start_date is null or end_date>=start_date)
);
create index if not exists agent_campaign_campaigns_agent_idx on public.agent_campaign_campaigns(agent_id,status);
create index if not exists agent_campaign_campaigns_month_idx on public.agent_campaign_campaigns(month_id);

create table if not exists public.agent_campaign_updates (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.agent_campaign_campaigns(id) on delete cascade,
  report_date date not null default current_date,
  spend numeric(14,2) not null default 0 check (spend>=0),
  reach bigint not null default 0 check (reach>=0),
  impressions bigint not null default 0 check (impressions>=0),
  profile_visits bigint not null default 0 check (profile_visits>=0),
  messages bigint not null default 0 check (messages>=0),
  leads bigint not null default 0 check (leads>=0),
  notes text,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  unique(campaign_id,report_date)
);
create index if not exists agent_campaign_updates_campaign_idx on public.agent_campaign_updates(campaign_id,report_date desc);

create or replace function public.touch_agent_campaign_updated_at()
returns trigger language plpgsql security invoker set search_path='' as $$ begin new.updated_at=now(); return new; end; $$;
do $$ declare t text; begin foreach t in array array['agent_campaign_user_permissions','agent_campaign_agents','agent_campaign_accounts','agent_campaign_months','agent_campaign_allocations','agent_campaign_campaigns'] loop
  execute format('drop trigger if exists %I on public.%I','touch_'||t,t);
  execute format('create trigger %I before update on public.%I for each row execute function public.touch_agent_campaign_updated_at()','touch_'||t,t);
end loop; end $$;

create or replace function public.agent_campaign_can_view_credentials()
returns boolean language sql stable security invoker set search_path='' as $$
  select (select public.agent_campaign_module_access()) and coalesce((select p.role='admin' or ap.can_view_credentials
    from public.profiles p left join public.agent_campaign_user_permissions ap on ap.user_id=p.id where p.id=(select auth.uid())),false);
$$;
create or replace function public.agent_campaign_can_manage_budget()
returns boolean language sql stable security invoker set search_path='' as $$
  select (select public.agent_campaign_module_access()) and coalesce((select p.role='admin' or ap.can_manage_budget
    from public.profiles p left join public.agent_campaign_user_permissions ap on ap.user_id=p.id where p.id=(select auth.uid())),false);
$$;

create or replace function public.agent_campaign_save_credential(p_account_id uuid,p_password text,p_login_email text default null,p_recovery_email text default null,p_recovery_phone text default null)
returns void language plpgsql security definer set search_path='' as $$
declare v_secret uuid; begin
  if (select auth.uid()) is null or not (select public.agent_campaign_can_view_credentials()) then raise exception 'Not authorized'; end if;
  if char_length(coalesce(p_password,''))<6 then raise exception 'Password must contain at least 6 characters'; end if;
  if not exists(select 1 from public.agent_campaign_accounts where id=p_account_id) then raise exception 'Account not found'; end if;
  select secret_id into v_secret from public.agent_campaign_credentials where account_id=p_account_id;
  if v_secret is null then
    select vault.create_secret(p_password,'agent-campaign-'||p_account_id::text,'TAAMEER Instagram account credential') into v_secret;
    insert into public.agent_campaign_credentials(account_id,secret_id,login_email,recovery_email,recovery_phone,updated_by)
    values(p_account_id,v_secret,nullif(btrim(p_login_email),''),nullif(btrim(p_recovery_email),''),nullif(btrim(p_recovery_phone),''),(select auth.uid()));
  else
    perform vault.update_secret(v_secret,p_password);
    update public.agent_campaign_credentials set login_email=nullif(btrim(p_login_email),''),recovery_email=nullif(btrim(p_recovery_email),''),recovery_phone=nullif(btrim(p_recovery_phone),''),last_rotated_at=now(),updated_by=(select auth.uid()),updated_at=now() where account_id=p_account_id;
  end if;
  update public.agent_campaign_accounts set credentials_saved=true,updated_by=(select auth.uid()) where id=p_account_id;
  insert into public.agent_campaign_credential_audit(account_id,actor_id,action) values(p_account_id,(select auth.uid()),'saved');
end; $$;

create or replace function public.agent_campaign_reveal_credential(p_account_id uuid)
returns table(login_email text,password text,recovery_email text,recovery_phone text,last_rotated_at timestamptz)
language plpgsql security definer set search_path='' as $$ begin
  if (select auth.uid()) is null or not (select public.agent_campaign_can_view_credentials()) then raise exception 'Not authorized'; end if;
  insert into public.agent_campaign_credential_audit(account_id,actor_id,action) values(p_account_id,(select auth.uid()),'revealed');
  return query select c.login_email,v.decrypted_secret,c.recovery_email,c.recovery_phone,c.last_rotated_at
    from public.agent_campaign_credentials c join vault.decrypted_secrets v on v.id=c.secret_id where c.account_id=p_account_id;
end; $$;

alter table public.agent_campaign_user_permissions enable row level security;
alter table public.agent_campaign_agents enable row level security;
alter table public.agent_campaign_accounts enable row level security;
alter table public.agent_campaign_credentials enable row level security;
alter table public.agent_campaign_credential_audit enable row level security;
alter table public.agent_campaign_months enable row level security;
alter table public.agent_campaign_allocations enable row level security;
alter table public.agent_campaign_campaigns enable row level security;
alter table public.agent_campaign_updates enable row level security;

do $$ declare t text; begin foreach t in array array['agent_campaign_agents','agent_campaign_accounts','agent_campaign_campaigns','agent_campaign_updates'] loop
  execute format('drop policy if exists %I on public.%I',t||'_select',t);
  execute format('create policy %I on public.%I for select to authenticated using ((select public.agent_campaign_module_access()))',t||'_select',t);
  execute format('drop policy if exists %I on public.%I',t||'_insert',t);
  execute format('create policy %I on public.%I for insert to authenticated with check ((select public.agent_campaign_module_access()))',t||'_insert',t);
  execute format('drop policy if exists %I on public.%I',t||'_update',t);
  execute format('create policy %I on public.%I for update to authenticated using ((select public.agent_campaign_module_access())) with check ((select public.agent_campaign_module_access()))',t||'_update',t);
  execute format('drop policy if exists %I on public.%I',t||'_delete',t);
  execute format('create policy %I on public.%I for delete to authenticated using ((select public.agent_campaign_module_access()))',t||'_delete',t);
end loop; end $$;

drop policy if exists agent_campaign_months_select on public.agent_campaign_months;
create policy agent_campaign_months_select on public.agent_campaign_months for select to authenticated using ((select public.agent_campaign_module_access()));
drop policy if exists agent_campaign_months_write on public.agent_campaign_months;
create policy agent_campaign_months_insert on public.agent_campaign_months for insert to authenticated with check ((select public.agent_campaign_can_manage_budget()));
create policy agent_campaign_months_update on public.agent_campaign_months for update to authenticated using ((select public.agent_campaign_can_manage_budget())) with check ((select public.agent_campaign_can_manage_budget()));
create policy agent_campaign_months_delete on public.agent_campaign_months for delete to authenticated using ((select public.agent_campaign_can_manage_budget()));
drop policy if exists agent_campaign_allocations_select on public.agent_campaign_allocations;
create policy agent_campaign_allocations_select on public.agent_campaign_allocations for select to authenticated using ((select public.agent_campaign_module_access()));
drop policy if exists agent_campaign_allocations_write on public.agent_campaign_allocations;
create policy agent_campaign_allocations_insert on public.agent_campaign_allocations for insert to authenticated with check ((select public.agent_campaign_can_manage_budget()));
create policy agent_campaign_allocations_update on public.agent_campaign_allocations for update to authenticated using ((select public.agent_campaign_can_manage_budget())) with check ((select public.agent_campaign_can_manage_budget()));
create policy agent_campaign_allocations_delete on public.agent_campaign_allocations for delete to authenticated using ((select public.agent_campaign_can_manage_budget()));

drop policy if exists agent_campaign_permissions_select on public.agent_campaign_user_permissions;
create policy agent_campaign_permissions_select on public.agent_campaign_user_permissions for select to authenticated using ((select public.agent_campaign_module_access()) and (user_id=(select auth.uid()) or exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='admin')));
drop policy if exists agent_campaign_permissions_admin on public.agent_campaign_user_permissions;
create policy agent_campaign_permissions_admin_insert on public.agent_campaign_user_permissions for insert to authenticated with check (exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='admin'));
create policy agent_campaign_permissions_admin_update on public.agent_campaign_user_permissions for update to authenticated using (exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='admin')) with check (exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='admin'));
create policy agent_campaign_permissions_admin_delete on public.agent_campaign_user_permissions for delete to authenticated using (exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='admin'));
-- Explicit deny policies document that credential tables are RPC-only.
drop policy if exists agent_campaign_credentials_rpc_only on public.agent_campaign_credentials;
create policy agent_campaign_credentials_rpc_only on public.agent_campaign_credentials for all to authenticated using (false) with check (false);
drop policy if exists agent_campaign_credential_audit_rpc_only on public.agent_campaign_credential_audit;
create policy agent_campaign_credential_audit_rpc_only on public.agent_campaign_credential_audit for all to authenticated using (false) with check (false);

grant execute on function public.agent_campaign_module_access() to authenticated;
grant execute on function public.agent_campaign_can_view_credentials() to authenticated;
grant execute on function public.agent_campaign_can_manage_budget() to authenticated;
grant execute on function public.agent_campaign_save_credential(uuid,text,text,text,text) to authenticated;
grant execute on function public.agent_campaign_reveal_credential(uuid) to authenticated;
grant select,insert,update,delete on public.agent_campaign_agents,public.agent_campaign_accounts,public.agent_campaign_months,public.agent_campaign_allocations,public.agent_campaign_campaigns,public.agent_campaign_updates to authenticated;
grant select,insert,update,delete on public.agent_campaign_user_permissions to authenticated;
revoke all on public.agent_campaign_credentials,public.agent_campaign_credential_audit from anon,authenticated;
revoke all on public.agent_campaign_agents,public.agent_campaign_accounts,public.agent_campaign_months,public.agent_campaign_allocations,public.agent_campaign_campaigns,public.agent_campaign_updates,public.agent_campaign_user_permissions from anon;
revoke all on function public.agent_campaign_save_credential(uuid,text,text,text,text) from public,anon;
revoke all on function public.agent_campaign_reveal_credential(uuid) from public,anon;

insert into public.agent_campaign_user_permissions(user_id,can_manage_budget,can_manage_accounts,can_view_credentials)
select id,true,true,true from public.profiles where id in ('9a68ff8c-f521-4ee6-8891-8b99baf1c772','4a0eac28-44de-4995-8a9b-5cdf08d369f0') on conflict(user_id) do update set can_manage_budget=true,can_manage_accounts=true,can_view_credentials=true;

insert into public.agent_campaign_months(month_start,total_budget,currency,status,notes)
values(date_trunc('month',current_date)::date,0,'QAR','planning','Set the monthly paid-media budget to begin allocations.') on conflict(month_start) do nothing;

insert into public.agent_campaign_agents(legacy_agent_id,full_name_en,full_name_ar,department_team,company_email,work_phone,employment_status,source)
values
('1','Mouna Fahem','منى فاهم','Operations','m.fahem@taameergroup.com','77709322','pending_hr','ig_sheet'),
('2','Daniel Ebrahimi','دانيال ابراهيمي','Operations','d.ebrahimi@taameergroup.com','77752562','pending_hr','ig_sheet'),
('3','Houda Gharbi','هدى الغربي','Operation','h.gharbi@taameergroup.com','70008367','pending_hr','ig_sheet'),
('4','Mahmood Davood Nuaimi','محمود داوود نعومي','Regional Brokerage Specialist','m.dawood@taameergroup.com','31110797','pending_hr','ig_sheet'),
('5','Nabila Taala','نبيلة',null,'n.taala@taameergroup.com','31119603','pending_hr','ig_sheet'),
('6','Rahma Thlijeni','رحمة الثليجاني','Operations','r.nasr@taameergroup.com','77664743','pending_hr','ig_sheet'),
('7','Asal Asasani','عسل',null,'a.sasani@taameergroup.com',null,'pending_hr','ig_sheet'),
('8','Abdelrahman Mahdi Abdelkader Abdelhay','عبدالرحمن',null,'a.abdelhay@taameergroup.com','70004205','pending_hr','ig_sheet'),
('9','Mohamed Zakaria','محمد زكريا',null,'za.mohamed@taameergroup.com','70006734','pending_hr','ig_sheet'),
('10','Muaadh Almaliki','معاذ',null,'m.almliki@taameergroup.com','70009280','pending_hr','ig_sheet'),
('11','Randi Raji Ahmad Abumathaned','رندا',null,'r.abumathaneh@taameergroup.com','70006965','pending_hr','ig_sheet'),
('12','Sara Mhirsi','سارة',null,'s.mhirsi@taameergroup.com','77977986','pending_hr','ig_sheet'),
('13','Abdulla Rahimi Shahvari','عبدالله',null,'a.shahvari@taameergroup.com','975 7797 7983','pending_hr','ig_sheet')
on conflict do nothing;

insert into public.agent_campaign_accounts(agent_id,username,profile_url,category,status,bio_status,profile_setup_status)
select a.id,v.username,v.profile_url,'Real Estate Agent',v.status,v.bio_status,v.setup_status from public.agent_campaign_agents a join (values
('m.fahem@taameergroup.com','mouna_taameer','https://www.instagram.com/mouna_taameer/','under_setup','done','done'),
('d.ebrahimi@taameergroup.com','daniel_taameer','https://www.instagram.com/daniel_taameer/','under_setup','done','done'),
('h.gharbi@taameergroup.com','houda_taameer','https://www.instagram.com/houda_taameer/','under_setup','done','done'),
('m.dawood@taameergroup.com','mahmood_taameer','https://www.instagram.com/mahmood_taameer/','under_setup','done','done'),
('n.taala@taameergroup.com','nabila_taameer','https://www.instagram.com/nabila_taameer/','setup_required','done','missing'),
('r.nasr@taameergroup.com','rahma_taameer','https://www.instagram.com/rahma_taameer/','under_setup','done','done'),
('a.sasani@taameergroup.com','asal_taameer','https://www.instagram.com/asal_taameer/','setup_required','code_needed','missing'),
('a.abdelhay@taameergroup.com','abdelrahman_taameer','https://www.instagram.com/abdelrahman_taameer/','setup_required','done','missing'),
('za.mohamed@taameergroup.com','mohamed_taameer','https://www.instagram.com/mohamed_taameer/','under_setup','done','done'),
('m.almliki@taameergroup.com','muaadh_taameer','https://www.instagram.com/muaadh_taameer/','setup_required','done','missing'),
('r.abumathaneh@taameergroup.com','randi_taameer','https://www.instagram.com/randi_taameer/','setup_required','code_needed','missing'),
('s.mhirsi@taameergroup.com',null,null,'no_account','missing','missing'),
('a.shahvari@taameergroup.com','abdullah.taameer','https://www.instagram.com/abdullah.taameer/','setup_required','done','missing')
) as v(email,username,profile_url,status,bio_status,setup_status) on lower(a.company_email)=lower(v.email)
on conflict(agent_id) do nothing;

update public.app_data set data=data||jsonb_build_array(jsonb_build_object(
  'id','agent-campaigns','name','Agent Campaigns','icon','fa-bullseye','desc','Sales agent Instagram readiness, budgets and lead campaigns',
  'color','#757575','roles',jsonb_build_array('admin','user'),'status','active','controlStatus','live',
  'maintenanceMessage','Agent Campaigns is currently under maintenance.'))
where id='modules' and not exists(select 1 from jsonb_array_elements(data) m where m->>'id'='agent-campaigns');
update public.app_data set data=jsonb_set(jsonb_set(data,'{admin,agent-campaigns}','{"view":true,"edit":true,"delete":true}'::jsonb,true),'{user,agent-campaigns}','{"view":true,"edit":true,"delete":false}'::jsonb,true) where id='permissions';
update public.profiles set modules=coalesce(modules,'[]'::jsonb)||'"agent-campaigns"'::jsonb where id in ('9a68ff8c-f521-4ee6-8891-8b99baf1c772','4a0eac28-44de-4995-8a9b-5cdf08d369f0') and not(coalesce(modules,'[]'::jsonb)?'agent-campaigns');
update public.app_data set data=(select jsonb_agg(case when u->>'id' in ('9a68ff8c-f521-4ee6-8891-8b99baf1c772','4a0eac28-44de-4995-8a9b-5cdf08d369f0') and not coalesce((u->'modules')?'agent-campaigns',false) then jsonb_set(u,'{modules}',coalesce(u->'modules','[]'::jsonb)||'"agent-campaigns"'::jsonb,true) else u end) from jsonb_array_elements(data) u) where id='users';
