-- TAAMEER Minutes module — private meeting records and per-record access.
create sequence if not exists public.meeting_minutes_reference_seq;

create or replace function public.minutes_module_access()
returns boolean language sql stable security invoker set search_path = '' as $$
  select coalesce((select p.status = 'active' and coalesce(p.modules, '[]'::jsonb) ? 'minutes'
    from public.profiles p where p.id = (select auth.uid())), false);
$$;

create or replace function public.set_meeting_minutes_reference()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if new.reference_code is null or btrim(new.reference_code) = '' then
    new.reference_code := 'MOM-MKT-' || to_char(coalesce(new.meeting_date, current_date), 'YYYY')
      || '-' || lpad(nextval('public.meeting_minutes_reference_seq')::text, 4, '0');
  end if;
  return new;
end;
$$;

create or replace function public.touch_meeting_minutes_updated_at()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin new.updated_at := now(); return new; end;
$$;

create table if not exists public.meeting_minutes (
  id uuid primary key default gen_random_uuid(),
  reference_code text not null unique,
  created_by uuid not null references public.profiles(id),
  title text not null check (char_length(btrim(title)) between 2 and 240),
  meeting_type text not null default 'team' check (meeting_type in ('team','one_to_one','management','chairman','external','private')),
  status text not null default 'draft' check (status in ('draft','in_progress','review','finalized','locked')),
  meeting_date date not null default current_date,
  start_time time,
  end_time time,
  location text,
  meeting_mode text not null default 'in_person' check (meeting_mode in ('in_person','online','hybrid')),
  confidentiality text not null default 'standard' check (confidentiality in ('standard','confidential','strict')),
  visibility text not null default 'attendees' check (visibility in ('private','attendees','selected','department')),
  agenda text not null default '',
  discussion_notes text not null default '',
  approvals_required text not null default '',
  follow_up_notes text not null default '',
  external_attendees jsonb not null default '[]'::jsonb check (jsonb_typeof(external_attendees) = 'array'),
  decisions jsonb not null default '[]'::jsonb check (jsonb_typeof(decisions) = 'array'),
  action_items jsonb not null default '[]'::jsonb check (jsonb_typeof(action_items) = 'array'),
  shared_with uuid[] not null default '{}'::uuid[],
  version integer not null default 1 check (version > 0),
  finalized_at timestamptz,
  locked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.meeting_minute_attendees (
  meeting_id uuid not null references public.meeting_minutes(id) on delete cascade,
  user_id uuid not null references public.profiles(id),
  attendee_role text not null default 'attendee' check (attendee_role in ('organizer','attendee','optional','observer')),
  viewed_at timestamptz,
  acknowledged_at timestamptz,
  created_at timestamptz not null default now(),
  primary key (meeting_id, user_id)
);

create table if not exists public.meeting_minute_views (
  meeting_id uuid not null references public.meeting_minutes(id) on delete cascade,
  user_id uuid not null references public.profiles(id),
  first_viewed_at timestamptz not null default now(),
  last_viewed_at timestamptz not null default now(),
  view_count integer not null default 1 check (view_count > 0),
  primary key (meeting_id, user_id)
);

create table if not exists public.meeting_minute_notifications (
  id bigint generated by default as identity primary key,
  meeting_id uuid not null references public.meeting_minutes(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id),
  actor_id uuid not null references public.profiles(id),
  event_type text not null check (event_type in ('shared','finalized','updated','action_assigned')),
  message text not null default 'A meeting record was shared with you.',
  seen_at timestamptz,
  created_at timestamptz not null default now(),
  check (recipient_id <> actor_id)
);

create index if not exists meeting_minutes_created_by_idx on public.meeting_minutes(created_by);
create index if not exists meeting_minutes_shared_with_idx on public.meeting_minutes using gin(shared_with);
create index if not exists meeting_minutes_date_idx on public.meeting_minutes(meeting_date desc);
create index if not exists meeting_minute_attendees_user_idx on public.meeting_minute_attendees(user_id);
create index if not exists meeting_minute_views_user_idx on public.meeting_minute_views(user_id);
create index if not exists meeting_minute_notifications_recipient_idx on public.meeting_minute_notifications(recipient_id, seen_at, created_at desc);
create index if not exists meeting_minute_notifications_actor_idx on public.meeting_minute_notifications(actor_id);
create unique index if not exists meeting_minute_notifications_once_idx on public.meeting_minute_notifications(meeting_id, recipient_id, event_type);

drop trigger if exists meeting_minutes_reference_trigger on public.meeting_minutes;
create trigger meeting_minutes_reference_trigger before insert on public.meeting_minutes
for each row execute function public.set_meeting_minutes_reference();
drop trigger if exists meeting_minutes_updated_trigger on public.meeting_minutes;
create trigger meeting_minutes_updated_trigger before update on public.meeting_minutes
for each row execute function public.touch_meeting_minutes_updated_at();

alter table public.meeting_minutes enable row level security;
alter table public.meeting_minute_attendees enable row level security;
alter table public.meeting_minute_views enable row level security;
alter table public.meeting_minute_notifications enable row level security;

drop policy if exists meeting_minutes_select on public.meeting_minutes;
create policy meeting_minutes_select on public.meeting_minutes for select to authenticated using (
  (select public.minutes_module_access()) and (created_by = (select auth.uid()) or
  (select auth.uid()) = any(shared_with) or (visibility = 'department' and confidentiality = 'standard'))
);
drop policy if exists meeting_minutes_insert on public.meeting_minutes;
create policy meeting_minutes_insert on public.meeting_minutes for insert to authenticated
with check ((select public.minutes_module_access()) and created_by = (select auth.uid()));
drop policy if exists meeting_minutes_update on public.meeting_minutes;
create policy meeting_minutes_update on public.meeting_minutes for update to authenticated
using ((select public.minutes_module_access()) and created_by = (select auth.uid()) and status <> 'locked')
with check ((select public.minutes_module_access()) and created_by = (select auth.uid()));
drop policy if exists meeting_minutes_delete on public.meeting_minutes;
create policy meeting_minutes_delete on public.meeting_minutes for delete to authenticated
using ((select public.minutes_module_access()) and created_by = (select auth.uid()) and status <> 'locked');

drop policy if exists meeting_attendees_select on public.meeting_minute_attendees;
create policy meeting_attendees_select on public.meeting_minute_attendees for select to authenticated
using ((select public.minutes_module_access()) and exists (select 1 from public.meeting_minutes m where m.id = meeting_id));
drop policy if exists meeting_attendees_insert_owner on public.meeting_minute_attendees;
create policy meeting_attendees_insert_owner on public.meeting_minute_attendees for insert to authenticated
with check ((select public.minutes_module_access()) and exists (select 1 from public.meeting_minutes m where m.id = meeting_id and m.created_by = (select auth.uid()) and m.status <> 'locked'));
drop policy if exists meeting_attendees_update on public.meeting_minute_attendees;
create policy meeting_attendees_update on public.meeting_minute_attendees for update to authenticated
using ((select public.minutes_module_access()) and (user_id = (select auth.uid()) or exists (select 1 from public.meeting_minutes m where m.id = meeting_id and m.created_by = (select auth.uid()) and m.status <> 'locked')))
with check ((select public.minutes_module_access()) and (user_id = (select auth.uid()) or exists (select 1 from public.meeting_minutes m where m.id = meeting_id and m.created_by = (select auth.uid()) and m.status <> 'locked')));
drop policy if exists meeting_attendees_delete_owner on public.meeting_minute_attendees;
create policy meeting_attendees_delete_owner on public.meeting_minute_attendees for delete to authenticated
using ((select public.minutes_module_access()) and exists (select 1 from public.meeting_minutes m where m.id = meeting_id and m.created_by = (select auth.uid()) and m.status <> 'locked'));

drop policy if exists meeting_views_select on public.meeting_minute_views;
create policy meeting_views_select on public.meeting_minute_views for select to authenticated
using ((select public.minutes_module_access()) and (user_id = (select auth.uid()) or exists (select 1 from public.meeting_minutes m where m.id = meeting_id and m.created_by = (select auth.uid()))));
drop policy if exists meeting_views_insert on public.meeting_minute_views;
create policy meeting_views_insert on public.meeting_minute_views for insert to authenticated
with check ((select public.minutes_module_access()) and user_id = (select auth.uid()) and exists (select 1 from public.meeting_minutes m where m.id = meeting_id));
drop policy if exists meeting_views_update on public.meeting_minute_views;
create policy meeting_views_update on public.meeting_minute_views for update to authenticated
using ((select public.minutes_module_access()) and user_id = (select auth.uid()))
with check ((select public.minutes_module_access()) and user_id = (select auth.uid()));

drop policy if exists meeting_notifications_select on public.meeting_minute_notifications;
create policy meeting_notifications_select on public.meeting_minute_notifications for select to authenticated
using ((select public.minutes_module_access()) and recipient_id = (select auth.uid()));
drop policy if exists meeting_notifications_insert on public.meeting_minute_notifications;
create policy meeting_notifications_insert on public.meeting_minute_notifications for insert to authenticated
with check ((select public.minutes_module_access()) and actor_id = (select auth.uid()) and recipient_id <> (select auth.uid())
  and exists (select 1 from public.meeting_minutes m where m.id = meeting_id and m.created_by = (select auth.uid()) and recipient_id = any(m.shared_with)));
drop policy if exists meeting_notifications_update on public.meeting_minute_notifications;
create policy meeting_notifications_update on public.meeting_minute_notifications for update to authenticated
using ((select public.minutes_module_access()) and recipient_id = (select auth.uid()))
with check ((select public.minutes_module_access()) and recipient_id = (select auth.uid()));

grant usage on sequence public.meeting_minutes_reference_seq to authenticated;
grant execute on function public.minutes_module_access() to authenticated;
grant execute on function public.set_meeting_minutes_reference() to authenticated;
grant execute on function public.touch_meeting_minutes_updated_at() to authenticated;
grant select, insert, update, delete on public.meeting_minutes to authenticated;
grant select, insert, update, delete on public.meeting_minute_attendees to authenticated;
grant select, insert, update on public.meeting_minute_views to authenticated;
grant select, insert, update on public.meeting_minute_notifications to authenticated;
revoke all on public.meeting_minutes, public.meeting_minute_attendees, public.meeting_minute_views, public.meeting_minute_notifications from anon;

update public.app_data set data = data || jsonb_build_array(jsonb_build_object(
  'id','minutes','name','Minutes','icon','fa-file-signature','desc','Private meeting records, decisions and follow-up actions',
  'color','#757575','roles',jsonb_build_array('admin','user'),'status','active','controlStatus','live',
  'maintenanceMessage','Meeting Minutes is currently under maintenance.'))
where id='modules' and not exists (select 1 from jsonb_array_elements(data) m where m->>'id'='minutes');

update public.app_data set data = jsonb_set(jsonb_set(data, '{admin,minutes}',
  '{"view":true,"edit":true,"delete":true}'::jsonb, true), '{user,minutes}',
  '{"view":true,"edit":true,"delete":true}'::jsonb, true) where id='permissions';

update public.profiles set modules = coalesce(modules,'[]'::jsonb) || '"minutes"'::jsonb
where id in ('9a68ff8c-f521-4ee6-8891-8b99baf1c772','4a0eac28-44de-4995-8a9b-5cdf08d369f0')
and not (coalesce(modules,'[]'::jsonb) ? 'minutes');

update public.app_data set data = (select jsonb_agg(case
  when u->>'id' in ('9a68ff8c-f521-4ee6-8891-8b99baf1c772','4a0eac28-44de-4995-8a9b-5cdf08d369f0')
    and not coalesce((u->'modules') ? 'minutes', false)
  then jsonb_set(u, '{modules}', coalesce(u->'modules','[]'::jsonb) || '"minutes"'::jsonb, true)
  else u end) from jsonb_array_elements(data) u) where id='users';
