// ---------- Accent / theme ----------
function applyAccentCSS(color) {
  const c = Utils.validColor(color);
  document.documentElement.style.setProperty('--accent', c);
  document.documentElement.style.setProperty('--accent-soft', c + '1F');
  document.documentElement.style.setProperty('--accent-hover', c + '38');
}
function applyActiveAccent() { applyAccentCSS(state.currentUser?.accentColor || state.settings.accent); }
function setAccent(el) { applySystemAccent(el.dataset.color, el.dataset.name); document.querySelectorAll('#colorPicker .color-swatch').forEach(s => s.classList.remove('active')); el.classList.add('active'); document.getElementById('customColor').value = el.dataset.color; document.getElementById('customColorHex').textContent = el.dataset.color; }
function setCustomAccent(color) { applySystemAccent(color, 'Custom'); document.querySelectorAll('#colorPicker .color-swatch').forEach(s => s.classList.remove('active')); document.getElementById('customColorHex').textContent = color; }
function applySystemAccent(color, name) { state.settings.accent = Utils.validColor(color); state.settings.accentName = name; if (!state.currentUser?.accentColor) applyAccentCSS(color); save(); }
function loadSystemAccent() { const s = state.settings; applyAccentCSS(s.accent || '#757575'); document.getElementById('customColor').value = Utils.validColor(s.accent); document.getElementById('customColorHex').textContent = Utils.validColor(s.accent); const swatch = document.querySelector(`#colorPicker .color-swatch[data-color="${s.accent}"]`); if (swatch) { document.querySelectorAll('#colorPicker .color-swatch').forEach(x => x.classList.remove('active')); swatch.classList.add('active'); } }
function setPersonalAccent(el) { applyPersonalAccent(el.dataset.color); document.querySelectorAll('#personalColorPicker .color-swatch').forEach(s => s.classList.remove('active')); el.classList.add('active'); document.getElementById('personalCustomColor').value = el.dataset.color; document.getElementById('personalCustomColorHex').textContent = el.dataset.color; }
function setPersonalCustomAccent(color) { applyPersonalAccent(color); document.querySelectorAll('#personalColorPicker .color-swatch').forEach(s => s.classList.remove('active')); document.getElementById('personalCustomColorHex').textContent = color; }
function applyPersonalAccent(color) { if (!state.currentUser) return; const c = Utils.validColor(color); state.currentUser.accentColor = c; const idx = state.users.findIndex(u => u.id === state.currentUser.id); if (idx !== -1) state.users[idx].accentColor = c; localStorage.setItem('taameer_currentUser', JSON.stringify({ id: state.currentUser.id })); applyAccentCSS(c); save(); }
function resetPersonalAccent() { if (!state.currentUser) return; state.currentUser.accentColor = null; const idx = state.users.findIndex(u => u.id === state.currentUser.id); if (idx !== -1) state.users[idx].accentColor = null; applyAccentCSS(state.settings.accent); refreshPersonalColorPicker(null); save(); }
function refreshPersonalColorPicker(color) { document.querySelectorAll('#personalColorPicker .color-swatch').forEach(s => s.classList.remove('active')); if (color) { const swatch = document.querySelector(`#personalColorPicker .color-swatch[data-color="${color}"]`); if (swatch) swatch.classList.add('active'); document.getElementById('personalCustomColor').value = color; document.getElementById('personalCustomColorHex').textContent = color; } else { document.getElementById('personalCustomColor').value = state.settings.accent; document.getElementById('personalCustomColorHex').textContent = state.settings.accent; } }
function toggleTheme() { const html = document.documentElement; html.classList.toggle('dark'); localStorage.setItem('taameer_theme', html.classList.contains('dark') ? 'dark' : 'light'); document.getElementById('darkToggle')?.classList.toggle('on', html.classList.contains('dark')); }
function loadTheme() { if (localStorage.getItem('taameer_theme') === 'dark') document.documentElement.classList.add('dark'); }
